### ISSUE TITLE
embed throws Minified React error #37

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-play#628]
Occasionally when loading a Play embed, the embed loads but the map doesn't draw, the bottom map progress barberpole never stops scrolling, and the console says:

> Uncaught (in promise) Error: Minified React error #37; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=37 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at r (VM1842 embedded.js:32)
    at Object._renderNewRootComponent (VM1842 embedded.js:31)
    at Object._renderSubtreeIntoContainer (VM1842 embedded.js:31)
    at Object.render (VM1842 embedded.js:31)
    at s (VM1842 embedded.js:43)
    at a (VM1842 embedded.js:44)

This seen at https://precog.mapzen.com/mapzen/mapzen-docs-generator/meetar/tutorial-divs/documentation/tangram/custom-styles/ after scrolling up and down without changing anything in the editors.

**Comment by louh** [comment]
@meetar The React error is thrown because it wants to display an error, but the embedded Play doesn't support modals at the moment. I've resolved this issue, but it didn't fix the underlying problem -- which is that some other error was thrown in the first place.

> Cannot read property 'error' of undefined
e.(anonymous function) @ VM873 embedded.js:formatted:37246
a @ VM873 embedded.js:formatted:74005
Promise.resolve (async)
(anonymous) @ tangram.min.js:formatted:27036
r @ VM873 embedded.js:formatted:37497

And some other (related?) Tangram warning:

> VM873 embedded.js:formatted:37246Tangram v0.11.7 [warn]: Caught exception in listener for event 'move': TypeError: Cannot read property 'move' of undefined
    at https://mapzen.com/tangram/0.11/tangram.min.js:18:3515
    at Array.forEach (native)
    at e.trigger (https://mapzen.com/tangram/0.11/tangram.min.js:18:3472)
    at Object.move (https://mapzen.com/tangram/0.11/tangram.min.js:12:24497)
    at https://mapzen.com/tangram/0.11/tangram.min.js:18:3528
    at Array.forEach (native)
    at e.trigger (https://mapzen.com/tangram/0.11/tangram.min.js:18:3472)
    at e.value (https://mapzen.com/tangram/0.11/tangram.min.js:18:28159)
    at e.value (https://mapzen.com/tangram/0.11/tangram.min.js:18:26195)
    at e.value (https://mapzen.com/tangram/0.11/tangram.min.js:12:13087)
    at t.updateSize (https://mapzen.com/tangram/0.11/tangram.min.js:11:6520)
    at HTMLDocument.hooks.visibilitychange (https://mapzen.com/tangram/0.11/tangram.min.js:11:6638)
    at HTMLDocument.r (https://precog.mapzen.com/tangrams/tangram-play/master/build/js/embedded.js:23:10780)

We might have to put our heads together (possibly with @bcamper) to narrow this one down. I'm not sure if "Cannot read property 'error' of undefined" refers to. It might be here in Tangram (https://github.com/tangrams/tangram/blob/bcb1ee700961167417534a208d4a85d41143636d/src/utils/worker_broker.js#L194) but how is `data` undefined if it's inside an if-statement that reads `data.type`? Or is it here (https://github.com/tangrams/tangram-play/blob/c1e40a8ce00bd4642ce6739aa5dac7a44e05eddd/src/js/tangram-play.js#L84) and `console` is somehow undefined at the moment?

**Comment by louh** [comment]
Follow up, after scrolling up and down some more: more than one kind of error can be thrown.

There's this:

> Uncaught TypeError: Cannot read property 'location' of null
    at a (embedded.js:44)
    at h (embedded.js:42)
    at g (embedded.js:42)
    at Me (embedded.js:4)
    at cr (embedded.js:5)
    at ir (embedded.js:5)
    at embedded.js:5
    at Ct (embedded.js:4)
    at or (embedded.js:5)
    at cs.setValue (embedded.js:5)
    at precog.mapzen.com/:361

Which traces to here (https://github.com/tangrams/tangram-play/blob/a55b24c424c506b4e955c5acf98fc9dcf6a82a5b/src/js/tools/url-state.js#L97) where `window` is undefined (!)

And:

> Uncaught TypeError: Cannot read property 'view_complete' of undefined

(No stack trace.)

This only happens in Chrome, and never seems to be a problem in Firefox. It raises some interesting questions about when these scripts are actually executing when the iframe is rebuilt...

**Comment by meetar** [comment]
I believe this is "fixed" with https://github.com/mapzen/documentation/commit/fb8b711b432f620acb0a7f805e824c7c00edecba, but it's ugly 👹

And I still don't understand the cause.

**Comment by meetar** [comment]
Welp - not "fixed" per se but the original issue is no longer present, so closing this as fixed and will open another issue elsewhere.

**Comment by umair-khanzada** [comment]
if you are using under development just used unminified version,
