### ISSUE TITLE
embed throws Leaflet error

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-play#655]
In https://precog.mapzen.com/mapzen/documentation/meetar/tutorial-divs/documentation/tangram/custom-styles/ - scrolling up and down will occasionally trigger this error:

>Tangram v0.11.7 [warn]: Caught exception in listener for event 'move': TypeError: Cannot read property 'move' of undefined
    at https://mapzen.com/tangram/0.11/tangram.min.js:18:3515
    at Array.forEach (native)
    at e.trigger (https://mapzen.com/tangram/0.11/tangram.min.js:18:3472)
    at Object.move (https://mapzen.com/tangram/0.11/tangram.min.js:12:24497)
    at https://mapzen.com/tangram/0.11/tangram.min.js:18:3528
    at Array.forEach (native)
    at e.trigger (https://mapzen.com/tangram/0.11/tangram.min.js:18:3472)
    at e.value (https://mapzen.com/tangram/0.11/tangram.min.js:18:28159)
    at e.value (https://mapzen.com/tangram/0.11/tangram.min.js:18:26559)
    at t.hooks.move (https://mapzen.com/tangram/0.11/tangram.min.js:11:2326)
    at t.fire (https://precog.mapzen.com/tangrams/tangram-play/master/build/js/embedded.js:14:16162)
    at t._onPanTransitionStep (https://precog.mapzen.com/tangrams/tangram-play/master/build/js/embedded.js:15:17390)
    at t.fire (https://precog.mapzen.com/tangrams/tangram-play/master/build/js/embedded.js:14:16162)
    at t._runFrame (https://precog.mapzen.com/tangrams/tangram-play/master/build/js/embedded.js:15:26299)
    at t._step (https://precog.mapzen.com/tangrams/tangram-play/master/build/js/embedded.js:15:26137)
    at t._animate (https://precog.mapzen.com/tangrams/tangram-play/master/build/js/embedded.js:15:26010)
>
> e.(anonymous function) @ embedded.js:formatted:37246
s @ VM1819 tangram.min.js:17
(anonymous) @ VM1819 tangram.min.js:18
trigger @ VM1819 tangram.min.js:18
value @ VM1819 tangram.min.js:18
value @ VM1819 tangram.min.js:18
hooks.move @ VM1819 tangram.min.js:11
fire @ embedded.js:formatted:22535
_onPanTransitionStep @ embedded.js:formatted:23900
fire @ embedded.js:formatted:22535
_runFrame @ embedded.js:formatted:24228
_step @ embedded.js:formatted:24221
_animate @ embedded.js:formatted:24216

which appears to originate at `node_modules/leaflet/src/dom/PosAnimation.js:53`.

When the error occurs, the editor pane loads but the map doesn't draw.

…possibly related to https://github.com/tangrams/tangram-play/issues/628 which appears to be caused by the editor being initialized somehow before it's attached to the dom.

**Comment by meetar** [comment]
Interestingly, this doesn't appear to occur with a local build.

**Comment by meetar** [comment]
"fixed" with https://github.com/mapzen/documentation/commit/fb8b711b432f620acb0a7f805e824c7c00edecba and https://github.com/mapzen/documentation/commit/0435acc5cd70db2a26a490e300d2bdc562dd66fb
